config/routes.rb
Rails.application.routes.draw do

  root 'people#index'

  resources :people

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
before_action :set_person, except: [:index, :new, :create]

  def index
    @people = Person.all
  end

  def show
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    if
      @person.save
      redirect_to people_path(@person)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @person.update(person_params)
      redirect_to person_path(@person)
    else
      render :edit
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to people_path
  end

  private
    def set_person
      @person = Person.find(params[:id])
    end

    def person_params
      params.require(:person).permit(:name, :age, :gender, :hair_color, :eye_color, :alive)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonalModelkas</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_forms.html.erb
<%= form_for @person do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :age %>
<%= f.number_field :age %>

<%= f.label :gender %>
<%= f.text_field :gender %>

<%= f.label :hair_color %>
<%= f.text_field :hair_color %>

<%= f.label :eye_color %>
<%= f.text_field :eye_color %>

<%= f.label :alive %>
<%= f.select :alive, [['Yes', true], ['No', false]] %>
<%= f.submit %>
<% end %>

app/views/people/edit.html.erb
<h3>Edit</h3>
<%= render(partial: 'forms') %>

app/views/people/index.html.erb
<h2> Everybody </h2>
<% if @people.any? %>

   <% @people.each do |person| %>
    <div>
      <%= person.id %>
      <%= person.name %>
       <%= link_to 'Show' , person_path  %>
    </div>
    <% end %>

<% else %>
  <h3>No People Found, Please Create One!</h3>
<% end %>

<hr />
<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h3>New</h3>
<%= render(partial: 'forms') %>

app/views/people/show.html.erb
<h3> <%= @person.name %> </h3>

<p> <%= @person.age %> </p>

<p> <%= @person.gender %> </p>

<p> <%= @person.hair_color %> </p>

<p> <%= @person.eye_color %> </p>

<p> <%= @person.alive %> </p>

<%= link_to 'Edit', edit_person_path(@person) %>
<%= link_to 'Destroy', person_path(@person), method: :delete %>